server:
 port: 8071
spring:
 application:
  name: "configserver"
 profiles:
    #active: native
    active: git
 rabbitmq:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"

 cloud:
   config:
     server:
       #native:
         #search-locations: "classpath:config"
        #search-locations: "file:///C://Users//harsh//config_prop"
      git:
       uri: "https://github.com/NanuCR7/microservices-config.git"
       default-label: main
       timeout: 5
       clone-on-start: true
       force-pull: true
encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
management:
  endpoints:
    web:
      exposure:
        include: "*"